---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  labels:
    author: intelliqit
    type: voting app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting app
  template:
    metadata:
      name: voting-pod
      labels:
        name: voting-app
    spec:
      containers:
        - name: voting
          image: dockersamples/examplevotingapp_vote
...
